=== Drcana/XML/portal_poverenika/src/main/resources/static/data/xsd/zahtev.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="zahtev_za_pristup_informacijama" xmlns:zahtev="zahtev_za_pristup_informacijama">
  <xs:element name="dokument_zahtev">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="naziv_organa" type="xs:string"/>
        <xs:element ref="zahtev:adresa"/>
        <xs:element name="naslov_dokumenta" type="xs:string"/>
        <xs:element name="zahtev_na_osnovu">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="zakon" type="xs:string"/>
              <xs:element ref="zahtev:napomena"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="lista_zahteva">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" ref="zahtev:zahtev"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="zahtev_se_odnosi_na">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="1" name="informacije" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="mesto_i_datum">
          <xs:complexType mixed="true">
            <xs:sequence maxOccurs="1" minOccurs="0">
              <xs:element name="mesto" type="xs:string"/>
              <xs:element name="datum" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="podnosilac_zahteva">
          <xs:complexType mixed="true">
            <xs:sequence maxOccurs="1" minOccurs="0">
              <xs:element name="ime">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:anyAttribute namespace="##any" processContents="lax"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="prezime">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:anyAttribute namespace="##any" processContents="lax"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element ref="zahtev:adresa"/>
              <xs:element name="drugi_podaci_za_kontakt" type="xs:string"/>
              <xs:element name="potpis" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="napomene">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="lista">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" ref="zahtev:napomena"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="naslov" use="required" type="xs:NCName"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="zahtev">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="zahtev:napomena"/>
        <xs:element name="lista_nacina">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="nacin" type="zahtev:nacin"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
      <xs:attribute name="check" use="required"/>
      <xs:attribute name="tip_zahteva" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="adresa">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ulica">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:anyAttribute namespace="##any" processContents="lax"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="broj">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:anyAttribute namespace="##any" processContents="lax"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="mesto">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:anyAttribute namespace="##any" processContents="lax"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="napomena">
    <xs:complexType mixed="true">
      <xs:attribute name="id" use="required" type="xs:integer"/>
      <xs:attribute name="labela"/>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="nacin">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="drugi_nacin" type="zahtev:drugi_nacin"/>
    </xs:sequence>
    <xs:attribute name="check" use="required"/>
    <xs:attribute name="tip_dostave" use="required" type="xs:NCName"/>
  </xs:complexType>
  <xs:complexType name="drugi_nacin">
    <xs:sequence>
      <xs:element name="sadrzaj" type="xs:string"/>
      <xs:element ref="zahtev:napomena"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Drcana/XML/spring/src/main/resources/static/data/xml/zahtev.xml
<dokument_zahtev xmlns="zahtev_za_pristup_informacijama" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="zahtev_za_pristup_informacijama  ../schemas/zahtev.xsd"
                 xmlns:pred="http://examples/predicate/">
    <naziv_organa></naziv_organa>
    <adresa>
        <mesto property="pred:mesto" datatype="xs:string">Subotica</mesto>
        <ulica property="pred:ulica" datatype="xs:string">Brace Radic</ulica>
        <broj property="pred:broj" datatype="xs:string">22</broj>
    </adresa>
    <naslov_dokumenta>
        З А Х Т Е В
        за приступ информацији од јавног значаја
    </naslov_dokumenta>

    <zahtev_na_osnovu>
        <zakon>
            На основу члана 15. ст. 1. Закона о слободном приступу информацијама од јавног значаја („Службени гласник
            РС“, бр. 120/04, 54/07, 104/09 и 36/10), од горе наведеног органа захтевам:
        </zakon>
        <napomena id="1"/>
    </zahtev_na_osnovu>

    <lista_zahteva>
        <zahtev tip_zahteva="posedovanje_informacije" check="">обавештење да ли поседује тражену информацију;</zahtev>
        <zahtev tip_zahteva="uvid_u_dokument" check="">увид у документ који садржи тражену информацију;⁫</zahtev>
        <zahtev tip_zahteva="kopija_dokumenta" check="">копију документа који садржи тражену информацију;</zahtev>
        <zahtev tip_zahteva="dostavljanje_kopije_dokumenta" check="">
            достављање копије документа који садржи тражену информацију
            <napomena id="2"/>
            <lista_nacina>
                <nacin tip_dostave="postom" check=""></nacin>
                <nacin tip_dostave="elektronski" check=""></nacin>
                <nacin tip_dostave="faksom" check=""></nacin>
                <nacin tip_dostave="drugi_nacin" check="">
                    <drugi_nacin>
                        <sadrzaj></sadrzaj>
                        <napomena id="3"/>
                    </drugi_nacin>
                </nacin>
            </lista_nacina>
        </zahtev>
    </lista_zahteva>

    <zahtev_se_odnosi_na>
        Овај захтев се односи на следеће информације:
        <informacije></informacije>
        навести што прецизнији опис информације која се
        тражи као и друге податке који олакшавају проналажење
        тражене информације
    </zahtev_se_odnosi_na>

    <mesto_i_datum>
        У  <mesto></mesto>,
        dana <datum></datum> godine
    </mesto_i_datum>

    <podnosilac_zahteva>
        <ime property="pred:ime" datatype="xs:string">Ime podnosioca</ime>
        <prezime property="pred:prezime" datatype="xs:string">Prezime podnosioca</prezime>
        Тражилац информације/Име и презиме
        <adresa>
            <ulica></ulica>
            <broj></broj>
            <mesto></mesto>
        </adresa>
        адреса
        <drugi_podaci_za_kontakt></drugi_podaci_za_kontakt>
        други подаци за контакт
        <potpis></potpis>
        Потпис
    </podnosilac_zahteva>

    <napomene naslov="Napomene">
        <lista>
            <napomena id="1" labela="*">У кућици означити која законска права на приступ информацијама желите да
                остварите.
            </napomena>
            <napomena id="2" labela="**">У кућици означити начин достављања копије докумената.</napomena>
            <napomena id="3" labela="***">Када захтевате други начин достављања обавезно уписати који начин достављања
                захтевате.
            </napomena>
        </lista>
    </napomene>
</dokument_zahtev>

=== Drcana/XML/portal_organa_vlasti/src/main/resources/static/data/xml/zahtev.xml
<zah:dokument_zahtev xmlns="http://www.ftn.uns.ac.rs/zahtev" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/zahtev  ../xsd/zahtev.xsd"
    xmlns:pred="http://examples/predicate/"
    xmlns:zah="http://www.ftn.uns.ac.rs/zahtev"
    xmlns:types="http://www.ftn.uns.ac.rs/types"
    about="http://www.ftn.uns.ac.rs/zahtev/1"
    id="1"
    userId="test@gmail.com"
    mesto="" datum="2021-01-01" property="pred:datum" datatype="xs:date" content="2021-01-01" >
   <organ_vlasti>
       <types:adresa>
           <types:mesto property="pred:mesto" datatype="xs:string">Subotica</types:mesto>
           <types:ulica property="pred:ulica" datatype="xs:string">Brace Radic</types:ulica>
           <types:broj property="pred:broj" datatype="xs:string">22</types:broj>
       </types:adresa>
       <types:naziv_organa property = "pred:naziv_organa"></types:naziv_organa>
   </organ_vlasti>
    
    <zah:naslov_dokumenta>
        З А Х Т Е В
        за приступ информацији од јавног значаја
    </zah:naslov_dokumenta>

    <zah:zakon>
        На основу члана 15. ст. 1. Закона о слободном приступу информацијама од јавног значаја („Службени гласник
        РС“, бр. 120/04, 54/07, 104/09 и 36/10), од горе наведеног органа захтевам:
        <zah:napomena id="1"/>
    </zah:zakon>

    <zah:lista_zahteva>
        <zah:zahtev tip_zahteva="posedovanje_informacije" checked="false">обавештење да ли поседује тражену информацију;
        </zah:zahtev>
        <zah:zahtev tip_zahteva="uvid_u_dokument" checked="false">увид у документ који садржи тражену информацију;⁫
        </zah:zahtev>
        <zah:zahtev tip_zahteva="kopija_dokumenta" checked="false">копију документа који садржи тражену информацију;
        </zah:zahtev>
        <zah:zahtev tip_zahteva="dostavljanje_kopije_dokumenta" checked="false">
            достављање копије документа који садржи тражену информацију
            <zah:napomena id="2"/>
            <zah:lista_nacina>
                <zah:nacin tip_dostave="postom" checked="false"></zah:nacin>
                <zah:nacin tip_dostave="elektronski" checked="false"></zah:nacin>
                <zah:nacin tip_dostave="faksom" checked="false"></zah:nacin>
                <zah:nacin tip_dostave="drugi_nacin" checked="false">
                    <zah:drugi_nacin>
                        <zah:sadrzaj></zah:sadrzaj>
                        <zah:napomena id="3"/>
                    </zah:drugi_nacin>
                </zah:nacin>
            </zah:lista_nacina>
        </zah:zahtev>
    </zah:lista_zahteva>

    <zah:informacije>
        Овај захтев се односи на следеће информације:
        <zah:sadrzaj_informacija></zah:sadrzaj_informacija>
        навести што прецизнији опис информације која се
        тражи као и друге податке који олакшавају проналажење
        тражене информације
    </zah:informacije>

    <zah:mesto_i_datum>
        У  <types:mesto></types:mesto>,
        dana <types:datum>2021-01-01</types:datum> godine
    </zah:mesto_i_datum>

    <zah:podnosilac_zahteva>
        <types:adresa>
            <types:mesto property="pred:mesto">Subotica</types:mesto>
            <types:ulica property="pred:ulica">Brace Ribnikara</types:ulica>
            <types:broj property="pred:broj">1</types:broj>
        </types:adresa>
        адреса
        <types:ime property="pred:ime" datatype="xs:string">Ime podnosioca</types:ime>
        <types:prezime property="pred:prezime" datatype="xs:string">Prezime podnosioca</types:prezime>
        Тражилац информације/Име и презиме
        <types:drugi_podaci_za_kontakt></types:drugi_podaci_za_kontakt>
        други подаци за контакт
        <types:potpis></types:potpis>
        Потпис
    </zah:podnosilac_zahteva>

    <zah:lista_napomena naslov="Napomene">
            <zah:napomena id="1" labela="*">У кућици означити која законска права на приступ информацијама желите да
                остварите.
            </zah:napomena>
            <zah:napomena id="2" labela="**">У кућици означити начин достављања копије докумената.</zah:napomena>
            <zah:napomena id="3" labela="***">Када захтевате други начин достављања обавезно уписати који начин
                достављања
                захтевате.
            </zah:napomena>
    </zah:lista_napomena>
</zah:dokument_zahtev>

=== Drcana/XML/portal_organa_vlasti/src/main/resources/static.data/xml/zahtev.xml
<zah:dokument_zahtev xmlns="zahtev_za_pristup_informacijama" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="zahtev_za_pristup_informacijama  ../xsd/zahtev.xsd"
                     xmlns:pred="http://examples/predicate/" xmlns:zah="zahtev_za_pristup_informacijama">
    <zah:naziv_organa></zah:naziv_organa>
    <zah:adresa>
        <zah:mesto property="pred:mesto" datatype="xs:string">Subotica</zah:mesto>
        <zah:ulica property="pred:ulica" datatype="xs:string">Brace Radic</zah:ulica>
        <zah:broj property="pred:broj" datatype="xs:string">22</zah:broj>
    </zah:adresa>
    <zah:naslov_dokumenta>
        З А Х Т Е В
        за приступ информацији од јавног значаја
    </zah:naslov_dokumenta>

    <zah:zahtev_na_osnovu>
        <zah:zakon>
            На основу члана 15. ст. 1. Закона о слободном приступу информацијама од јавног значаја („Службени гласник
            РС“, бр. 120/04, 54/07, 104/09 и 36/10), од горе наведеног органа захтевам:
        </zah:zakon>
        <zah:napomena id="1"/>
    </zah:zahtev_na_osnovu>

    <zah:lista_zahteva>
        <zah:zahtev tip_zahteva="posedovanje_informacije" check="">обавештење да ли поседује тражену информацију;
        </zah:zahtev>
        <zah:zahtev tip_zahteva="uvid_u_dokument" check="">увид у документ који садржи тражену информацију;⁫
        </zah:zahtev>
        <zah:zahtev tip_zahteva="kopija_dokumenta" check="">копију документа који садржи тражену информацију;
        </zah:zahtev>
        <zah:zahtev tip_zahteva="dostavljanje_kopije_dokumenta" check="">
            достављање копије документа који садржи тражену информацију
            <zah:napomena id="2"/>
            <zah:lista_nacina>
                <zah:nacin tip_dostave="postom" check=""></zah:nacin>
                <zah:nacin tip_dostave="elektronski" check=""></zah:nacin>
                <zah:nacin tip_dostave="faksom" check=""></zah:nacin>
                <zah:nacin tip_dostave="drugi_nacin" check="">
                    <zah:drugi_nacin>
                        <zah:sadrzaj></zah:sadrzaj>
                        <zah:napomena id="3"/>
                    </zah:drugi_nacin>
                </zah:nacin>
            </zah:lista_nacina>
        </zah:zahtev>
    </zah:lista_zahteva>

    <zah:zahtev_se_odnosi_na>
        Овај захтев се односи на следеће информације:
        <zah:informacije></zah:informacije>
        навести што прецизнији опис информације која се
        тражи као и друге податке који олакшавају проналажење
        тражене информације
    </zah:zahtev_se_odnosi_na>

    <zah:mesto_i_datum>
        У  <zah:mesto></zah:mesto>,
        dana <zah:datum></zah:datum> godine
    </zah:mesto_i_datum>

    <zah:podnosilac_zahteva>
        <zah:ime property="pred:ime" datatype="xs:string">Ime podnosioca</zah:ime>
        <zah:prezime property="pred:prezime" datatype="xs:string">Prezime podnosioca</zah:prezime>
        Тражилац информације/Име и презиме
        <zah:adresa>
            <zah:ulica></zah:ulica>
            <zah:broj></zah:broj>
            <zah:mesto></zah:mesto>
        </zah:adresa>
        адреса
        <zah:drugi_podaci_za_kontakt></zah:drugi_podaci_za_kontakt>
        други подаци за контакт
        <zah:potpis></zah:potpis>
        Потпис
    </zah:podnosilac_zahteva>

    <zah:napomene naslov="Napomene">
        <zah:lista>
            <zah:napomena id="1" labela="*">У кућици означити која законска права на приступ информацијама желите да
                остварите.
            </zah:napomena>
            <zah:napomena id="2" labela="**">У кућици означити начин достављања копије докумената.</zah:napomena>
            <zah:napomena id="3" labela="***">Када захтевате други начин достављања обавезно уписати који начин
                достављања
                захтевате.
            </zah:napomena>
        </zah:lista>
    </zah:napomene>
</zah:dokument_zahtev>
