=== Drcana/XML/spring/src/main/resources/static/data/schemas/resenje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="resenje" elementFormDefault="qualified"
    xmlns:res="resenje">

    <xs:element name="resenje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="informacije_o_resenju">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="datum_resenja" type="xs:date"/>
                            <xs:element name="datum_pondosenja_zahteva" type="xs:date"/>
                            <xs:element name="trazilac" type="res:TFizicko_lice"/>
                            <xs:element name="organ" type="res:TPravno_lice"/>
                            <xs:element name="poverenik">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ime">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="prezime">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                  <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="broj_resenja"/>
                        <xs:attribute name="tip_resenja" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sadrzaj_resenja">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="opis_resenja">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="telo_resenja" type="res:TParagrafi"/>
                            <xs:element name="obrazlozenje" type="res:TParagrafi"/>
                            <xs:element name="uputstvo" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="mesto">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ulica">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="broj" type="xs:positiveInteger"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element ref="res:adresa"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TPravno_lice">
        <xs:complexContent>
            <xs:extension base="res:TLice">
                <xs:sequence>
                    <xs:element name="naziv">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="res:TLice">
                <xs:sequence>
                    <xs:element name="ime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="prezime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TParagrafi">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="paragraf" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Drcana/XML/spring/src/main/resources/static/data/xml/resenje.xml
<?xml version="1.0" encoding="UTF-8"?>
<resenje xmlns="resenje"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="resenje ../schemas/resenje.xsd">
    <informacije_o_resenju>
        <datum_resenja>2020-11-11</datum_resenja>
        <datum_pondosenja_zahteva>2020-10-10</datum_pondosenja_zahteva>
        <trazilac>
            <adresa>
                <mesto>ns</mesto>
                <ulica>npr</ulica>
                <broj>11</broj>
            </adresa>
            <ime>a</ime>
            <prezime>a</prezime>
        </trazilac>
        <organ>
            <adresa>
                <mesto>ns</mesto>
                <ulica>qwert</ulica>
                <broj>13</broj>
            </adresa>
            <naziv>faks</naziv>
        </organ>
        <poverenik>
            <ime>pera</ime>
            <prezime>peric</prezime>
        </poverenik>
    </informacije_o_resenju>
    <sadrzaj_resenja>
        <opis_resenja>Повереник за информације од јавног значаја и заштиту података о личности, у поступку по алби
            коју је изјавио AA....
        </opis_resenja>
        <telo_resenja>
            <paragraf>Р Е Ш Е Њ Е</paragraf>
        </telo_resenja>
        <obrazlozenje>
            <paragraf>О б р а з л о ж е њ е</paragraf>
        </obrazlozenje>
        <uputstvo>Упутство о правном средству:</uputstvo>
    </sadrzaj_resenja>
</resenje>
