=== Drcana/XML/spring/src/main/resources/static/data/schemas/zalbaProtivOdluke.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="zalba_protiv_odluke" xmlns:zalba="zalba_protiv_odluke">
  <xs:element name="zalba_protiv_odluke">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="vrsta_zalbe" type="xs:string"/>
        <xs:element name="informacije_o_primaocu_zalbe">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="primalac_zalbe" type="xs:string"/>
              <xs:element ref="zalba:adresa"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="naslov" type="xs:string"/>
        <xs:element name="podaci_o_zaliocu">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element name="naziv" type="xs:string"/>
              <xs:element ref="zalba:adresa"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="podaci_o_organu">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element name="naziv_organa" type="xs:string"/>
              <xs:element name="resenje_zahteva">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="broj_resenja" type="xs:string"/>
                    <xs:element name="datum" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="detalji_zalbe">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element name="datum" type="xs:string"/>
              <xs:element name="razlog_zalbe" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="mesto_i_datum">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element name="mesto" type="xs:string"/>
              <xs:element name="datum" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="podaci_o_podnosiocu_zalbe">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element name="ime" type="xs:string"/>
              <xs:element name="prezime" type="xs:string"/>
              <xs:element ref="zalba:adresa"/>
              <xs:element name="drugi_podaci_za_kontakt" type="xs:string"/>
              <xs:element name="potpis" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="napomena">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="lista_napomena">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="stavka">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute default="napomena1" name="id" type="xs:string"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute default="Napomena:" name="title" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="adresa">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="mesto" type="xs:string"/>
        <xs:element name="ulica" type="xs:string"/>
        <xs:element name="broj" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Drcana/XML/spring/src/main/resources/static/data/xml/zalbaProtivOdluke.xml
<?xml version="1.0" encoding="UTF-8"?>
<zpo:zalba_protiv_odluke xmlns:zpo="zalba_protiv_odluke" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="zalba_protiv_odluke ../schemas/zalbaProtivOdluke.xsd"
                         xmlns:pred="http://examples/predicate/">
    <zpo:id></zpo:id>
    <zpo:vrsta_zalbe>
        ЖАЛБА ПРОТИВ ОДЛУКЕ ОРГАНА ВЛАСТИ КОЈОМ ЈЕ
        ОДБИЈЕН ИЛИ ОДБАЧЕН ЗАХТЕВ ЗА ПРИСТУП ИНФОРМАЦИЈИ
    </zpo:vrsta_zalbe>

    <zpo:informacije_o_primaocu_zalbe>
        <zpo:primalac_zalbe>
            Поверенику за информације од јавног значаја и заштиту података о личности
        </zpo:primalac_zalbe>
        <zpo:adresa>
            <mesto property="pred:mesto" datatype="xs:string">Београд</mesto>
            ,
            <ulica property="pred:ulica" datatype="xs:string">Булевар краља Александрa</ulica>
            бр.
            <broj property="pred:broj">15</broj>
        </zpo:adresa>
    </zpo:informacije_o_primaocu_zalbe>

    <zpo:naslov>Ж А Л Б А</zpo:naslov>

    <zpo:podaci_o_zaliocu>
        <zpo:naziv property="pred:naziv" datatype="xs:string">Никола Николић</zpo:naziv>
        <zpo:adresa>
            <mesto property="pred:mesto" datatype="xs:string">Нови Сад</mesto>
            <ulica property="pred:ulica" datatype="xs:string">Булевар Цара Лазара</ulica>
            <broj property="pred:broj">13</broj>
        </zpo:adresa>
        (Име, презиме, односно назив, адреса и седиште жалиоца)
    </zpo:podaci_o_zaliocu>

    <zpo:podaci_o_organu>
        против решења-закључка
        <zpo:naziv_organa property="pred:naziv_organa" datatype="xs:string">Назив органа</zpo:naziv_organa>
        (назив органа који је донео одлуку)
        <zpo:resenje_zahteva>
            Број <zpo:broj_resenja>071-01-1114/2020-03</zpo:broj_resenja> од <zpo:datum property="pred:datum_resenja">20.01.2020.</zpo:datum> године.
        </zpo:resenje_zahteva>
    </zpo:podaci_o_organu>

    <zpo:detalji_zalbe>
        Наведеном одлуком органа власти (решењем, закључком, обавештењем у писаној форми са елементима одлуке) ,
        супротно закону, одбијен-одбачен је мој захтев који сам поднео/ла-упутио/ла дана
        <zpo:datum>20.02.2020.</zpo:datum>
        године и тако ми ускраћено-онемогућено остваривање уставног и законског права на слободан приступ информацијама
        од јавног значаја. Oдлуку побијам у целости, односно у делу којим
        <zpo:razlog_zalbe></zpo:razlog_zalbe>
        јер није заснована на Закону о слободном приступу информацијама од јавног значаја.
        На основу изнетих разлога, предлажем да Повереник уважи моју жалбу, поништи одлука првостепеног органа и омогући
        ми приступ траженој/им информацији/ма.
        Жалбу подносим благовремено, у законском року утврђеном у члану 22. ст. 1. Закона о слободном приступу
        информацијама од јавног значаја.
    </zpo:detalji_zalbe>

    <zpo:mesto_i_datum>
        У <mesto></mesto> ,
        дана <datum>20.02.2020.</datum> године
    </zpo:mesto_i_datum>

    <zpo:podaci_o_podnosiocu_zalbe>
        <zpo:ime></zpo:ime>
        <zpo:prezime></zpo:prezime>
        Подносилац жалбе / Име и презиме
        <zpo:adresa>
            <mesto></mesto>
            <ulica></ulica>
            <broj>13</broj>
        </zpo:adresa>
        адреса
        <zpo:drugi_podaci_za_kontakt></zpo:drugi_podaci_za_kontakt>
        други подаци за контакт
        <zpo:potpis></zpo:potpis>
        потпис
    </zpo:podaci_o_podnosiocu_zalbe>

    <zpo:napomena title="Napomena:">
        <zpo:lista_napomena>
            <zpo:stavka id="napomena1">У жалби се мора навести одлука која се побија (решење, закључак, обавештење), назив
                органа који је одлуку донео, као и број и датум одлуке.
                Довољно је да жалилац наведе у жалби у ком погледу је незадовољан одлуком, с тим да жалбу не мора
                посебно образложити.
                Ако жалбу изјављује на овом обрасцу, додатно образложење може посебно приложити.
            </zpo:stavka>
            <zpo:stavka id="napomena2">Уз жалбу обавезно приложити копију поднетог захтева и доказ о његовој
                предаји-упућивању органу као и копију одлуке органа која се оспорава жалбом.
            </zpo:stavka>
        </zpo:lista_napomena>
    </zpo:napomena>
</zpo:zalba_protiv_odluke>
